# Generated by Django 4.2 on 2023-04-28 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='tanggal',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='waktu',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
