# Generated by Django 4.2 on 2023-04-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userlocation_schedulemember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlocation',
            old_name='user_id',
            new_name='user',
        ),
    ]
